# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  嘀嗒嘀嗒 || fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# 页脚设置
footer:
  owner:
    enable: true
    since: 2020
  custom_text: <a href="http://beian.miit.gov.cn/"><img class="icp-icon" src="https://i.loli.net/2021/07/12/K2DLFGesgZNuhYm.png"><span>豫ICP备17030789号-1</span></a> | 欢迎来到我们的世界呀! | 本网站由<a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"><img class="icp-icon" src="https://i.loli.net/2021/07/12/VubIOKPs2p9eNWz.png"></a>提供CDN加速/云存储服务
# 侧边信息设置
runtimeshow:
  enable: true
  publish_date: 6/13/2020 00:00:00  
  ##網頁開通時間

# 404 页面
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: 
